- name: Set up NAT on inetRouter
  block:
    - name: disable and stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
    - name: install iptables
      yum:
        name:
        - iptables
        - iptables-services
        state: present
        update_cache: true
    
    - name: copy iptables config
      template: 
        src: iptables
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600

    - name: start and enable iptables service
      service: 
          name: iptables
          state: restarted
          enabled: true
  when: (ansible_hostname == "inetRouter")

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
    reload: true
  when: "'routers' in group_names"

# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0  
- name: disable default route
  lineinfile: 
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0  
    line: DEFROUTE=NO
  when: (ansible_hostname != "inetRouter")

# echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
- name: add default gateway for centralRouter
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.1
  when: (ansible_hostname == "centralRouter")

# echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
- name: add default gateway for centralServer
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
  when: (ansible_hostname == "centralServer")

- name: add default gateway for office1Router
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.9
  when: (ansible_hostname == "office1Router")