- name: set up route on office1Server
  template:
    src: office1Server_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "office1Server")
    
- name: set up route on office2Server
  template:
    src: office2Server_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "office2Server")

- name: set up route on centralRouter eth1
  template:
    src: centralRouter_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "centralRouter")

- name: set up route on office1Router eth1
  template:
    src: office1Router_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "office1Router")

- name: set up route on inetRouter
  template:
    src: inetRouter_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "inetRouter")

- name: restart network
  service: 
    name: network
    state: restarted

- name: restart network
  service: 
    name: network
    state: restarted
